# Generated by Django 3.1.6 on 2021-02-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
